[package]
name = "doumi"
version = "0.1.0"
description = "A very simple text-format based on a deadfish interpreter"
edition = "2021"

[dependencies]
clap = {version = "4.0.26", features = ['derive'] }
rustyline = "10.0.0"
rustyline-derive = "0.7.0"

